### ISSUE TITLE
For 2013 'Sending 2000 bytes over commodity network' number is 0.0ns

### ISSUE THREAD

**Issue by kumarshantanu** [colin-scott/interactive_latencies#2]
Visit http://www.eecs.berkeley.edu/~rcs/research/interactive_latency.html and move slider to the year 2013. You will notice *Send 2000 bytes over commodity network* value to be `0.0ns` which does not seem right. The micro-seconds value is OK.

**Comment by cdman** [comment]
I think this is fixed - at least I can't reproduce it any more. Could you please re-check and report if the issue is still happening?

BTW, the link now is http://people.eecs.berkeley.edu/~rcs/research/interactive_latency.html

**Comment by kumarshantanu** [comment]
@cdman Yes, it seems fixed now.

**Comment by AllenzhLi** [comment]
2020  Send 2000 bytes over commodity network value 44ns < memory 100ns which does not seem right.
